### ISSUE TITLE
Send Digit option Missing!!!

### ISSUE THREAD

**Issue by amanshah28** [fedeamura/flutter_twilio#2]

**Comment by Erchil66** [comment]
how does send digits actually? am quite also having quite confused on this one

**Comment by fedeamura** [comment]
this is currently not implemented

**Comment by amanshah28** [comment]
@federico are you planning for update this library.?

**Comment by fedeamura** [comment]
in a short term, no. maybe in a few weeks

**Comment by fedeamura** [comment]
@amanshah28 
@juanmadelboca implemented it on https://github.com/fedeamura/flutter_twilio/pull/4
